/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject3;

public class App {
    

    public static void main(String[] args) {
        RegCar c1 = new RegCar("Tata","Tiago","Petrol",5,19);
        System.out.println(c1.brand);
        ElecCar c2 = new ElecCar("Kia","EV6","Electric",5,77);
        HybridCar c3 = new HybridCar("Toyota","Innova Hycross","electric & petrol",7,1208);
        
        ElecBike b1 = new ElecBike("Pure EV","EcoDryft","Electric",101,171);
        SportsBike b2 = new SportsBike("Kawasaki","Ninja H2 SX","Petrol",260,330);
        
        Truck t1 = new Truck("Eicher","Pro 1095","Diesel",7220,6);

    }
}
