/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject3;

public class Vehicle {
    protected String brand, model,fuel_type;

    Vehicle(String brand, String model, String fuel_type){
        this.brand = brand;
        this.model = model;
        this.fuel_type = fuel_type;
    }
}
